SignalRChat.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace SignalRChat.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

SignalRChat.Web/Controllers/SpeechRecognitionController.cs
using SignalRChat.Web.Services;
using System.Threading.Tasks;
using System.Web.Http;

namespace SignalRChat.Web.Controllers
{
    public class SpeechRecognitionController : ApiController
    {
        // POST api/<controller>
        public async Task<IHttpActionResult> Post(string connectionId)
        {
            var service = new SpeechRecognitionService();

            var content = await Request.Content.ReadAsByteArrayAsync();

            service.Recognice(connectionId, content);

            return Ok();
        }
    }
}

SignalRChat.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Chat";
}

<input type="hidden" id="chatUser" />
<input type="hidden" id="colorUserChat" />

<div class="row " style="padding-top:40px;">
    <div class="col-md-9 col-lg-offset-1">
        <h3 class="text-center">Chat SignalR With Speech Cognitive Service</h3>
    </div>
    <div class="col-md-2">
        <img class="img-responsive" src="~/Content/images/LogoBanner01.png" />
    </div>

    <br /><br />
    <div class="col-md-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                SALA
            </div>
            <div class="panel-body">
                <ul id="chatRoom" class="media-list"></ul>
            </div>
            <div class="panel-footer">
                <div class="input-group">
                    <input id="message" type="text" class="form-control" placeholder="Ingrese su mensaje" />
                    <span class="input-group-btn">
                        <button id="micro" class="btn btn-info" type="button">
                            <i class="fa fa-microphone fa-1x" aria-hidden="true"></i> Grabar
                        </button>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <!--Script references. -->
    <!--The jQuery library is required and is referenced by default in _Layout.cshtml. -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="@Url.Content("~/signalr/hubs")"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script>
        var urls = {
            speech: '@Url.Action("POST", "SpeechRecognition", new { httproute = "DefaultApi" })'
        };
    </script>

    <script src="~/Scripts/Index.js"></script>
}

SignalRChat.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - NETRAF 2017</title>
    @Styles.Render("~/styles/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container-fluid">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>
    <script src="~/Scripts/recorder.js"></script>
    <script src="~/Scripts/bootstrap-notify.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>